### ISSUE TITLE
Pack doesn't work on Windows with Py

### ISSUE THREAD

**Issue by robotrader** [openiap/vscode-assistent#1]
Hi!
I have created test python project as described in the OpenIAP docs.
Project is located in folder c:\tmp\openiappy\

Local tests works fine - it connects to OpenIAP instance and prints some output.

But when I tried to pack&deploy - error occured: Failed to pack project, c:\tmp\openiappy\openiappy-0.0.7.tgz + " does not exist.
I cant't see any verbose logs for investigation of problem...

**Comment by skadefro** [comment]
What is the name inside package.json? If this contains / or \ npm pack will fail

**Comment by robotrader** [comment]
My package.json content

`{
    "name": "openiappy",
    "version": "0.0.7",
    "description": "Example agent, please change",
    "main": "main.py",
    "openiap": {
        "daemon": false,
        "chromium": false,
        "language": "python"
    }
}`

**Comment by robotrader** [comment]
npm is manager for NodeJS, isn't it?
I am trying to deploy python project...

**Comment by skadefro** [comment]
Yes, but openflow uses project.json for all, to get information about how to run the package and what the  entry point is
```
"main": "main.py", "openiap": { "daemon": false, "chromium": false, "language": "python" }
```
the vs code extension is written in nodejs and to avoid sending to many npm modules with the extension i use the npm module "built into" vs code, to pack the files before uploading them to openflow.
So 
```
 error occured: Failed to pack project, c:\tmp\openiappy\openiappy-0.0.7.tgz + " does not exist.
 ```
 means something when wrong in that process. This does not look like an npm error, but an error from my extension. ( [here](https://github.com/openiap/vscode-assistant/blob/ae2a255e20af81418c69ccfd321958ad942b7a7a/src/flowconfig.ts#L284) )  It seems openiappy-0.0.7.tgz is not in the folder after calling npm pack. I've seen that happen for windows machines when the package name has / or \ in it.
 If that is not the case, then I'm a little out of good ideas. Try looking under the "output" tab and select "openiap" after you tried a publish, this should show more information about where the file is, or if something went wrong doing the pack

**Comment by robotrader** [comment]
I have installed NodeJS from https://nodejs.org/en/download/prebuilt-installer
Pack&Publish works without any errors.

**Comment by skadefro** [comment]
That is interesting. vs.code is a nodejs app and does not require node or npm to be pre-installed.
I assumed using vs.code's interface for doing npm commands would the also work without npm installed, but this suggest that is not the case.
I will need to test that more, but for now i guess i need to add a message some where telling people npm needs to be pre-installed (?)
